version: '3.8'

services:
    postgres:
        container_name: posttest-postgres-database
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: lottery888
            POSTGRES_USER: posttest
            POSTGRES_PASSWORD: p@ssword888
        volumes:
            - ./db-prepare/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - backend-network

    springbootapp:
        container_name: posttest-spring-boot-lottery-shop
        build:
            context: .
            dockerfile: Dockerfile
        image: posttest-springbootapp-lottery
        ports:
            - "8888:8888"
        depends_on:
            - postgres
        environment:
            SPRING_DATASOURCE_URL: ${DATABASE_URL}
            SPRING_DATASOURCE_USERNAME: posttest
            SPRING_DATASOURCE_PASSWORD: p@ssword888
            SPRING_PROFILES_ACTIVE: prod
        networks:
            - backend-network

networks:
    backend-network:
        driver: bridge
