version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: lottery888
      POSTGRES_USER: posttest
      POSTGRES_PASSWORD: p@ssword888
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  pgdata:
